# Generated by Django 5.2.4 on 2025-08-01 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='filme',
            name='diretor',
            field=models.CharField(default='Diretor Desconhecido', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='filme',
            name='titulo',
            field=models.CharField(max_length=200),
        ),
    ]
